name: run Weather_Station.py

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout the repository content
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env
      - run: echo TOKEN_GMAIL | base64 -d > token.pickle
        env:
          TOKEN_GMAIL: ${{ secrets.TOKEN_GMAIL }}
      - run: echo CLIENT_SECRET_GMAIL | base64 -d > client_secret_114502949276-qujopcn3v6e65fdkjm1f7mikmdcicbad.apps.googleusercontent.com.json
        env:
          CLIENT_SECRET_GMAIL: ${{ secrets.CLIENT_SECRET_GMAIL }}
      
      - run: python Weather_Station.py
        
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
